[package]
description = "PROMISE (PROactive MultIsignature SEcurity) protocol for PoS Multisign"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "promise-core"
version = "2.0.2"
edition = "2021"

[dependencies]
cfx-types = { path="../../cfx_types" }
frost-core = { version = "1.0", features = ["internals", "serde"] }
frost-secp256k1 = { version = "1.0", features = ["serde"] }
serde = { version = "1.0.124", features = ["derive"] }
group = "^0.13"
tiny-keccak = "^2.0.2"