[package]
name = "cfxcore-types"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
license-file.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfx-types = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }