name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "nightly-2024-02-04"
          
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Generate documentation
        run: |
          rustup default nightly-2024-02-04 && RUSTDOCFLAGS='--enable-index-page -Z unstable-options' cargo +nightly-2024-02-04 doc --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc